export const ACTION_TYPES = {
  GET_BOARDS: "GET_BOARDS",
  GET_BOARDS_SUCCESS: "GET_BOARDS_SUCCESS",
  GET_BOARDS_ERROR: "GET_BOARDS_ERROR",

  ADD_BOARD: "ADD_BOARD",
  DELETE_BOARD: "DELETE_BOARD",

  GET_LISTS: "GET_LISTS",
  GET_LISTS_SUCCESS: "GET_LISTS_SUCCESS",
  GET_LISTS_ERROR: "GET_LISTS_ERROR",
  GET_FILTERED_LISTS: "GET_FILTERED_LISTS",

  ADD_LIST: "ADD_LIST",
  MOVE_LIST: "MOVE_LIST",

  DELETE_LIST: "DELETE_LIST",
  DELETE_LIST_SUCCESS: "DELETE_LIST_SUCCESS",
  DELETE_LIST_ERROR: "DELETE_LIST_ERROR",

  ADD_CARD: "ADD_CARD",
  DELETE_CARD: "DELETE_CARD",
  MOVE_CARD: "MOVE_CARD",
};

// add action creators
